In [1]:
import numpy as np
b=np.array([2,2,2,])
b

array([2, 2, 2])

In [2]:
y = np.array([[2,2,2],[2,2,2],[2,2,2]])
y

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [3]:
type(y)

numpy.ndarray

In [4]:
a=np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [5]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [6]:
np.ones(4)

array([1., 1., 1., 1.])

In [7]:
np.empty(5)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 0.00000000e+000,
       0.00000000e+000])

In [8]:
np.arange(3,9,3)

array([3, 6])

In [9]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [10]:
np.arange(3,9)

array([3, 4, 5, 6, 7, 8])

In [11]:
np.linspace(0,50, num=5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [12]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
np.ones(4,dtype=np.int64)

array([1, 1, 1, 1], dtype=int64)

In [14]:
np.ones(4,dtype=np.int32)

array([1, 1, 1, 1])

In [15]:
y.size

9

In [16]:
y.shape

(3, 3)

In [17]:
n=np.arange(5)
n

array([0, 1, 2, 3, 4])

In [18]:
n[3]

3

In [19]:
n[0:]

array([0, 1, 2, 3, 4])

In [20]:
n[2:]

array([2, 3, 4])

In [21]:
n[0:4]

array([0, 1, 2, 3])

In [22]:
n[-2:]

array([3, 4])

In [23]:
np.arange(4)

array([0, 1, 2, 3])

In [24]:
y

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [25]:
y2= np.array([[3,4,5],[4,5,7],[6,7,8]])
y2

array([[3, 4, 5],
       [4, 5, 7],
       [6, 7, 8]])

In [26]:
type(y)

numpy.ndarray

In [27]:
y.ndim

2

In [28]:
 y*3

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [31]:
y+y2

array([[ 5,  6,  7],
       [ 6,  7,  9],
       [ 8,  9, 10]])

In [35]:
x=np.concatenate((y,y2))
x

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [3, 4, 5],
       [4, 5, 7],
       [6, 7, 8]])

In [36]:
x.ndim

2

In [51]:
x.reshape(3,6)

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 2, 3, 4, 5],
       [4, 5, 7, 6, 7, 8]])

In [48]:
o=x[np.newaxis,:]
o.shape

(1, 6, 3)

In [50]:
o.reshape(3,6,1)

array([[[2],
        [2],
        [2],
        [2],
        [2],
        [2]],

       [[2],
        [2],
        [2],
        [3],
        [4],
        [5]],

       [[4],
        [5],
        [7],
        [6],
        [7],
        [8]]])

In [52]:
print(o[o<5])

[2 2 2 2 2 2 2 2 2 3 4 4]


In [53]:
print(o[o>=5])

[5 5 7 6 7 8]


In [56]:
g2=o[o%2==0]
g2

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 6, 8])

In [58]:
o.max()

8

In [59]:
c=o[(o>2)&(o<8)]
c

array([3, 4, 5, 4, 5, 7, 6, 7])